language: node_js
branches:
  only:
    - master
before_install: bundle install
before_script: npm install -g grunt-cli
script: grunt build
deploy:
  provider: s3
  access_key_id: AKIAILDI32JHP7R3V75A
  secret_access_key: 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
  bucket: leungportfolio3.1x