language: node_js
branches:
  only:
  - master
before_install: bundle install
before_script: npm install -g grunt-cli
script: grunt build
deploy:
  provider: s3
  access_key_id: AKIAJJLZSLJXQBVDPS3Q
  secret_access_key:
    secure: tsPXVh1PMRnqgS6G7n8vFzMc6ISLLuDUq9s0OAEZAMsTPf74FHqrw5sLY9RmNpHt4qxrovv4znu4PP3Zt8A6z6w4yfuPONpZQtbXt+DTLC0T0MOeKY283xvrQsOcju2jGy7IuzUVJoV3veJwwGMPGgzfgwHN5urTrylcC9HH0JI=
  bucket: leungportfolio3.1
  acl: public_read
  region: us-west-2
  local_dir: dist
  on:
    repo: gleung93/Portfolio-3.1
